version: '3.8'

services:
  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - soa-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Auth Service
  auth-service:
    image: auth-service:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=${AUTH_MONGO_URI:-mongodb+srv://thang:123@cluster-soa-final.m1tinrp.mongodb.net/auth-db}
      - JWT_SECRET=${JWT_SECRET:-tuanjwtsecret}
    networks:
      - soa-network
    depends_on:
      - rabbitmq

  # Inventory Service
  inventory-service:
    image: inventory-service:latest
    volumes:
      - shared-images:/app/public/img
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGO_URI=${INVENTORY_MONGO_URI:-mongodb+srv://thang:123@cluster-soa-final.m1tinrp.mongodb.net/inventory-db}
    networks:
      - soa-network


  # Order Service
  order-service:
    image: order-service:latest

    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URI=${ORDER_MONGO_URI:-mongodb+srv://thang:123@cluster-soa-final.m1tinrp.mongodb.net/order-db}
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    networks:
      - soa-network
    depends_on:
      - rabbitmq

    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  # Notification Service
  notification-service:
    image: notification-service:latest

    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MONGO_URI=${NOTIFICATION_MONGO_URI:-mongodb+srv://thang:123@cluster-soa-final.m1tinrp.mongodb.net/notification-db}
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
      - EMAIL=tenk8595@gmail.com
      - EMAIL_PASSWORD=nhsu elfh hewr cahq
      - HOSTNAME={{.Node.Hostname}}-{{.Service.Name}}-{{.Task.Slot}}
    networks:
      - soa-network
    depends_on:
      - rabbitmq
    deploy:
      replicas: 2
      restart_policy:
        condition: any


  # Activity Service
  activity-service:
    image: activity-service:latest

    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - MONGO_URI=${ACTIVITY_MONGO_URI:-mongodb+srv://thang:123@cluster-soa-final.m1tinrp.mongodb.net/activity-db}
    networks:
      - soa-network

  # Report Service
  report-service:
    image: report-service:latest

    ports:
      - "3006:3006"
    environment:
      - EMAIL=tenk8595@gmail.com
      - EMAIL_PASSWORD=nhsu elfh hewr cahq
      - PORT=3006
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
      - MONGO_URI=${REPORT_MONGO_URI:-mongodb+srv://thang:123@cluster-soa-final.m1tinrp.mongodb.net/report-db}
    networks:
      - soa-network
    depends_on:
      - rabbitmq
      - order-service

  # API Gateway
  api-gateway:
    image: api-gateway:latest

    ports:
      - "2000:2000"
    environment:
      - PORT=2000
    networks:
      - soa-network
    depends_on:
      - auth-service
      - inventory-service
      - order-service
      - notification-service
      - activity-service
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  # Frontend
  frontend:
    image: frontend:latest
    volumes:
      - shared-images:/app/public/img
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - soa-network
    depends_on:
      - api-gateway

networks:
  soa-network:
    driver: overlay
    attachable: true

volumes:
  rabbitmq_data:
    driver: local
  shared-images:
    driver: local
